name: NPM Packages

on:
  push:
    branches:
      - main
      - dev
    paths:
      - packages
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - run: mkdir /var/tmp/.artifacts
      - run: yarn workspaces foreach --no-private pack --out /var/tmp/.artifacts/%s-%v.tgz
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: artifact
          path: /var/tmp/.artifacts
  publish:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.7
        with:
          name: artifact
          path: .
      - name: Publish NPM tarballs
        uses: reactway/npm-multi-publish-action@v0.1.0
        with:
          token: ${{ secrets.NPM_REGISTRY_TOKEN }}
