name: NPM Packages

on:
  push:
    branches:
      - main
      - dev
    paths:
      - server
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - run: mkdir /var/tmp/.artifacts  
      - run: yarn workspaces foreach --no-private pack --out /var/tmp/.artifacts/%s-%v.tgz
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          path: /var/tmp/.artifacts
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.6
      - name: Publish to NPM 
        uses: author/action-publish@stable
        with:
          registry: https://npm.pkg.github
        env:
          NPM_TOKEN: ${{ secrets.CR_PAT }}
        
