name: Server PR

on:
  pull_request:
    branches: 
      - main
      - dev
    paths: 
      - server
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
