name: Server

on:
  pull_request:
    branches: 
      - main
      - dev
    paths: 
      - server
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: ./server
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          registry: ghcr.io
          tags: |
            reactway/server:latest
            reactway/server:${{ steps.package-version.outputs.current-version}}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

