name: Server

on:
  pull_request:
    branches: 
      - main
      - dev
    paths: 
      - server
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: ./server
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
#       - name: Login to DockerHub
#         uses: docker/login-action@v1 
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: MartynasZilinskas
          password: ${{ secrets.CR_PAT }}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: |
            ghcr.io/reactway/server:latest
            ghcr.io/reactway/server:${{ steps.package-version.outputs.current-version}}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
