name: Server

on:
  pull_request:
    branches: 
      - main
      - dev
    paths: 
      - server
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: server/
      - name: Build Docker
        uses: docker/build-push-action@v1
        with:
          context: server/
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: ghcr.io
          push: true
          tags: |
            reactway/server:latest
            reactway/server:${{ steps.package-version.outputs.current-version}}
          
 
